### ISSUE TITLE
Push v0.7.3 to crates.io

### ISSUE THREAD

**Issue by andyblarblar** [pimeys/rust-web-push#29]
Hello, I'm aware this repo is more or less unmaintained, but I figured this would be simpler than dealing with a fork. At the moment #22, which updated to tokio v1, is not available on any published version of this repo. Since it looks like master is stable, it would be very helpful if you could push this version (even as a beta perhaps) to crates.io such that we can use it as a dependency. Without this version bump, this crate cannot run on the latest versions of most web frameworks due to tokio versioning. Thanks.

**Comment by megrogan** [comment]
In the meantime could use a git reference in your cargo.toml:

web-push = { git = "ssh://github.com/pimeys/rust-web-push", ref = "85870ec55badfb95d74d1c7bd354a0deb5193481" }

**Comment by andyblarblar** [comment]
> In the meantime could use a git reference in your cargo.toml:
> 
> web-push = { git = "ssh://github.com/pimeys/rust-web-push", ref = "85870ec55badfb95d74d1c7bd354a0deb5193481" }

This is what I've been doing, and it does work in development. It is worth pointing out however that you cannot upload crates with a git dependency, so this isn't really a fix.

**Comment by andyblarblar** [comment]
Closing as v0.8 was published in 4cac72a2ca2e6c8414f9ac49fcf41609ab35ac28 😁

**Comment by pimeys** [comment]
If somebody wants to take admin here, you're all welcome!

**Comment by andyblarblar** [comment]
> If somebody wants to take admin here, you're all welcome!

I'd be happy to take up a maintainer role, if that's what you mean. I don't currently have any real repositories to look out for, so it would be nice to pick this up - particularly now that I know the codebase well.
