### ISSUE TITLE
web-push fails if notification is to be sent to Firefox

### ISSUE THREAD

**Issue by hamza1311** [pimeys/rust-web-push#48]
The library does not set `Authorization` header on the outgoing request to the push service endpoint. Mozilla's service fails with if this is not provided.

See more:  
- [Autopush HTTP documentation](https://autopush.readthedocs.io/en/latest/http.html)
- _Application Server Self-Identification_ in [the VAPID RFC](https://datatracker.ietf.org/doc/rfc8292/)
- [Common issues with firefox when sending notifications](https://web.dev/push-notifications-common-issues-and-reporting-bugs/#firefox-and-mozilla-autopush)

**Comment by andyblarblar** [comment]
Firefox has worked fine with my tests of this library since a fix a few versions ago (Fixing this issue https://github.com/mozilla-services/autopush-rs/issues/361). Make sure you're using the most recent version of this crate, or provide a minimal example of the issue otherwise.

**Comment by hamza1311** [comment]
It was an issue on my end where dependency conflicts meant I didn't get the latest versions. Works fine on latest update. Thanks for the help!
