### ISSUE TITLE
Web-push not working with chrome FCM

### ISSUE THREAD

**Issue by summonmayank** [pimeys/rust-web-push#51]
- Web-push client seems to be working fine with firefox and edge but not with chrome.
- Seems like while sending push request to `fcm` it requires "Host" header as part of the request. Which is not currently added (Which I believe might be the issue).
- I tested with Postman and it seems like fcm returns 404 Not Found if "Host" header is not present.
- I tried to hack the request_builder and add the "Host" header and send it via hyper-tls client, although it worked with firefox but again not with chrome.

I am not sure what might be going wrong. Any suggestions are appreciated. Thanks !

**Comment by andyblarblar** [comment]
Hey, I'm not able to test this ATM, but what did you find that said Google requires the host header? There's nearly no docs on googles web push API from what I can find so I'm not sure where I would start for this. Chrome was definitely working previously, so if it's stopped it's from an undocumented change

**Comment by summonmayank** [comment]
@andyblarblar It might be possible that `fcm.googleapis.com` is blocked from our firewall. I am currently looking into that. I'll get back to you once I confirm it.
