### ISSUE TITLE
Carve out a new release

### ISSUE THREAD

**Issue by andyblarblar** [pimeys/rust-web-push#58]
Just a reminder to myself to bump the version on crates.io now that some fixes have come in.

**Comment by naskya** [comment]
I don’t mean to be pushy, but can I ask you if this is going to happen in the near future? I’ve been pinning the commit hash in my `Cargo.toml` for months because I need the new feature.

**Comment by andyblarblar** [comment]
> I don’t mean to be pushy, but can I ask you if this is going to happen in the near future? I’ve been pinning the commit hash in my `Cargo.toml` for months because I need the new feature.

Oop, I'll do this soon, guess it fell off a todo list at some point

**Comment by andyblarblar** [comment]
All done!

**Comment by naskya** [comment]
Thank you!
